name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build java project
    runs-on: [ self-hosted, aws ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.6
    - name: Get project version
      id: version
      uses: lorislab/samo-action@v0.1.0-alpha4
      with:
        args: samo project version        
    - name: Set project version
      run: mvn versions:set -DnewVersion=${{ steps.version.outputs.stdout }}
    - name: Build with Maven
      run: mvn clean package -DskipTests