name: quarkus

on:
  workflow_call:

jobs:
  docker:
    name: build and push
    runs-on: [ self-hosted, aws ]
    env:
      DOCKER_CONFIG: $HOME/.docker
      SAMO_DOCKER_FILE: src/main/docker/Dockerfile
      SAMO_DOCKER_REGISTRY: harbor.1000kit.org
      SAMO_DOCKER_GROUP: '1000kit/'
      SAMO_DOCKER_TAG_TEMPLATE_LIST: '{{ .Version }}'  
      SAMO_DOCKER_RELEASE_REGISTRY: harbor.1000kit.org
      SAMO_DOCKER_RELEASE_GROUP: '1000kit/'
      SAMO_DOCKER_SKIP_OPENCONTAINERS_LABELS: 'false'
      SAMO_DOCKER_CONTEXT: '.'
      SAMO_DOCKER_SKIP_PULL: 'false'
      SAMO_DOCKER_BUILD_PUSH: 'false'
      SAMO_DOCKER_SKIP_DEV: 'false'
      SAMO_DOCKER_REMOVE_INTERMEDIATE_IMG_SKIP: 'false'      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: package
        path: target
    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: ${{ env.SAMO_DOCKER_REGISTRY }}
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}        
    - name: docker build
      uses: lorislab/samo-action@v1.0.0
      with:
        entrypoint: samo
        args: project docker build -v debug
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.6
    - name: Integration test
      run: mvn -B failsafe:integration-test failsafe:verify --file pom.xml
    - name: docker push
      uses: lorislab/samo-action@v1.0.0
      with:
        entrypoint: samo
        args: project docker push -v debug 
