name: quarkus

on:
  workflow_call:

jobs:
  maven:
    name: build and test
    runs-on: [ self-hosted, aws ]
    container:
      image: harbor.1000kit.org/1000kit/quarkus-build:v11
      options: --user root
      credentials:
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get project version
      id: version
      run: |
        tmp=$(samo project version)
        echo '::set-output name=VERSION::$tmp'
    - name: Set project version
      run: mvn versions:set -DnewVersion=${{ steps.version.outputs.VERSION }}
    - name: Build with Maven
      run: mvn -B clean package verify --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: target
        retention-days: 1
        if-no-files-found: ignore