name: quarkus

on:
  workflow_call:

jobs:
  maven:
    name: build and test
    runs-on: [ self-hosted, aws ]
    steps:
    - name: Use Docker in rootless mode.
      uses: ScribeMD/rootless-docker@0.1.7
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.6
    - name: Get project version
      id: version
      uses: lorislab/samo-action@v1.0.0
      with:
        args: samo project version        
    - name: Set project version
      run: mvn versions:set -DnewVersion=${{ steps.version.outputs.stdout }}
    - name: Build with Maven
      run: mvn -B clean package verify --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: target
        retention-days: 1
        if-no-files-found: ignore